import { Manrope } from "next/font/google";
import "./globals.css"; // Import your global CSS file

const manrope = Manrope({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Include the font stylesheet */}
        {/* <link rel="stylesheet" href={manrope.toStylesheet().href} /> */}
      </head>
      <body className={manrope.className}>{children}</body>
    </html>
  );
}
